services:
  thermal_segmentation:
    image: thermal-segmentor:latest
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          cpus: '0.20'
          memory: 12G
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
    volumes:
      - /home/phm/Datasets:/data
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
